config/routes.rb
Passitdown::Application.routes.draw do

root 'items#index'
resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def index
	@items = Item.all
end

def new
	@item =Item.new
end

def create
Item.create(item_params)
redirect_to root_path
end

private

def item_params
	params.require(:item).permit(:name, :address, :description)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<h1 class= "header">Pass it Down</h1>

<% @items.each do |item| %>
<div class="booyah-box  col-xs-10 col-xs-offset-1">
	<h2><%= item.name %></h2><br />
    <i><%= item.address %></i><br />
    <p><%= item.description %></p><br />
</div>
<% end %>

app/views/items/new.html.erb
<div <div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter your Item <h1><br />
	<%= simple_form_for @item do |f| %>
	<%= f.input :name %>
	<%= f.input :address %>
    <%= f.input :description %><br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passitdown</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
         <%= link_to 'Pass it Down', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
      		<%= link_to new_item_path do %>
      		<i class="glyphicon glyphicon-plus-sign"></i>
    		NEW ITEM
    		<% end %>
    	</li>
                
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>



<%= yield %>

</body>
</html>